pipeline {
    agent any

    environment {
        REGISTRY = "farzzit"
        IMAGE = "studentmang-app"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'master', url: 'https://github.com/medaminehammami/student-management-devops.git'
            }
        }

        stage('Build with Maven') {
            steps {
                dir('student-man-main') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Dependency Check') {
            steps {
                dir('student-man-main') {
                    sh '''
                    echo "🔍 Running OWASP Dependency-Check (light scan)..."
                    mvn org.owasp:dependency-check-maven:check \
                        -Dformat=HTML \
                        -DfailBuildOnCVSS=7 \
                        -DskipAssembly=true
                    '''
                }
            }
            post {
                always {
                    archiveArtifacts artifacts: 'student-man-main/target/dependency-check-report.html', allowEmptyArchive: true
                }
            }
        }

        stage('Run SonarQube Analysis') {
            environment {
                SONARQUBE = credentials('sonarqube-token')
            }
            steps {
                dir('student-man-main') {
                    withSonarQubeEnv('SonarQube') {
                        sh '''
                            mvn sonar:sonar \
                              -Dsonar.projectKey=studentmang-app \
                              -Dsonar.host.url=http://192.168.49.2:32000 \
                              -Dsonar.login=$SONARQUBE
                        '''
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('student-man-main') {
                    sh 'docker build -t $REGISTRY/$IMAGE:latest .'
                }
            }
        }

        stage('Trivy Scan (Security)') {
            steps {
                dir('student-man-main') {
                    sh '''
                    echo "🛠️  Pre-downloading Trivy vulnerability database..."
                    trivy --config /dev/null image --download-db-only || true

                    echo "🔍 Scanning Docker image for HIGH and CRITICAL vulnerabilities..."
                    trivy image --ignore-unfixed --scanners vuln  --light  --timeout 25m --exit-code 0 --severity HIGH,CRITICAL $REGISTRY/$IMAGE:latest
                    '''
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                dir('student-man-main') {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh '''
                            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                            docker push $REGISTRY/$IMAGE:latest
                            docker logout
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo '✅ Build, Dependency Check, Security Scan, and Push completed successfully!'
        }
        failure {
            echo '❌ Pipeline failed. Check logs for more details.'
        }
    }
}
